config/routes.rb
FlashDeals::Application.routes.draw do
  get "user/create"
  get "user/show"
  get "user/edit"
  get "deals/nearby" => 'deals#nearby'
  resources :deals
 

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => "deals#index"

  
end

app/models/deal.rb
class Deal < ActiveRecord::Base
	resourcify

	belongs_to :user

	geocoded_by :geo_address
  after_validation :geocode, if: :address_change

  def user_params 
  	params.require(:user).permit(:deal)
  end

  def geo_address
    self.address = self.street1+", "+self.city+", "+self.state+", "+self.zip.to_s
    self.address
  end

  def address_change
    if :street1_changed? || :city_changed? || :state_changed? || :zip_changed?
      true
    end
  end



end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  has_many :deals

  with_options if: :vendor_role? do |vendor|
    vendor.validates :street1, :presence => :true
    vendor.validates :city, :presence => :true
    vendor.validates :state, :presence => :true
    vendor.validates :zip, :presence => :true
  end

  geocoded_by :geo_address
  after_validation :geocode, if: :address_change

  def user_params 
  	params.require(:user).permit(:first_name, :last_name, :email, :street1, :street2, :city, :state, :zip, :latitude, :longitude, :phone)
  end

  # attr_accessible :role_ids
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def vendor_or_above_roles
  	self.has_role?(:vendor) || self.has_role?(:admin)
  end

  def vendor_role?
    self.has_role?(:vendor)
  end

  def geo_address
    self.address = self.street1+", "+self.city+", "+self.state+", "+self.zip.to_s
    self.address
  end

  def address_change
    if :street1_changed? || :city_changed? || :state_changed? || :zip_changed?
      true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]
  before_action :check_is_vendor, only: [:create]

  def check_is_vendor
    if current_user.has_role?(:vendor)
      return true
    else
      redirect_to :root, error: "You can't create deals"
    end
  end

  # def initialize(attributes = nil)
  #   attr_with_defaults  
  # end

  def current_deals
    if params[:start_time] && params[:end_time]
     @deals = Deals.find(:all, :conditions => {:dateTime.now => start_date..end_date})
    end
  end

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
    # OLD CODE--- this will give me the first 3 deals in the db
    # @limit_deals = Deal.find(:all, :order => "id desc", :limit =>3)
    # @ret_array = []
    # @deals.each do |deal|
    #   @ret_array << deal.attributes
    # end
    # @some_deals = @ret_array.to_json.html_safe

    # THE CODE BELOW IS FROM BEFORE THE ADDRESS WAS REMOVED FROM THE USER AND PLACED ON THE DEAL
    # @deals = Deal.includes(:user).find(:all, :order => "id desc", :limit => 3)
    # @ret_arr = []
    # @deals.each do |deal|
    #   if deal.user
    #     @ret_arr << deal.attributes.merge(deal.user.attributes.slice("latitude","longitude"))
    #   else
    #     @ret_arr << deal.attributes
    #   end
    # end
    # @some_deals = @ret_arr.to_json.html_safe
    # # @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
    @deal.street1 = current_user.street1
    @deal.city = current_user.city
    @deal.state = current_user.state
    @deal.zip = current_user.zip
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)
    @deal.user_id = current_user.id

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deal }
      else
        format.html { render action: 'new' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end

  def nearby
    latitude = params[:latitude]
    longitude = params[:longitude]
    d = Deal.where("start_time <= :now AND end_time >= :now", {now: DateTime.now}, :order => "id desc", :limit =>3)
    deals_nearby = d.near([latitude, longitude], 3)
    render json: deals_nearby
    # render json: {:latitude => latitude}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:deal, :description, :start_time, :end_time, :user_id, :street1, :city, :state, :zip, :address)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  def create
    build_resource(sign_up_params)
    resource.add_role(params[:user][:roles])

    if resource.save
      #render text: "Thank you for registering! You will receive a text message shortly with verification instructions."
      
        # Instantiate a Twilio client
        client = Twilio::REST::Client.new(TWILIO_CONFIG['sid'], TWILIO_CONFIG['token'])
      
        # Create and send an SMS message
        client.account.sms.messages.create(
          from: TWILIO_CONFIG['from'],
          to: @user.phone,
          body: "Thanks for signing up. To verify your account, please reply HELLO to this message."
        )
      yield resource if block_given?
      if resource.active_for_authentication?
        
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :email, :phone, :password, :street1, :city, :state, :zip, :latitude, :longitude) }
    end
end

app/controllers/users_controller.rb
class UserController < ApplicationController
  def create

  end

  def show
  	@user = current_user
  end

  def edit
  	@user = current_user
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
	
		

end

app/helpers/deals_helper.rb
module DealsHelper
	def get_deals
		Deal.get_all.to_json.html_safe
	end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_helper.rb
module UserHelper
	def get_deals
		User.get_all.to_json.html_safe
	end
end

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deal %><br>
    <%= f.text_field :deal %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= f.label :street_1 %>
  <%= f.text_field  :street1 %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip %>
  <%= f.text_field :zip %>


  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing deals</h1>

<table>
  <thead>
    <tr>
      <th>Deal</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    
   
    <script type="text/javascript">

    
    


    function initialize() {

      var initialLocation;
      var infos = [];
      var siberia = new google.maps.LatLng(60, 105);
      var newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
      var browserSupportFlag =  new Boolean();
      var dealsNearby = [];
      var infowindow = new google.maps.InfoWindow();

      var myOptions = {
        zoom: 14,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);
      var image = '/assets/smiley_happy.png'; 

      // Try W3C Geolocation (Preferred)
      if(navigator.geolocation) {
        browserSupportFlag = true;
        navigator.geolocation.getCurrentPosition(function(position) {
          initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
          var Person_marker = new google.maps.Marker({
            position: initialLocation,
            title:"Where I am!",
            map: map,
            animation: google.maps.Animation.DROP,
            icon: image
          }); 

          $.ajax('/deals/nearby',{
            type: "GET",
            dataType: "json",
            data: {latitude: position.coords.latitude, longitude: position.coords.longitude},
            success: function(data){
              map_deals(data);
              // console.log(data);
              // console.log(data.length);
              $("#nearby-deals").html("");
              var $table = $("<table><tr style='font-weight:bold'><td id='deal-name'>Deal Name</td><td id='deal-description'>Description</td><td><span id='deal-countdown'>Countdown</span></td></tr></table>");
              for(var i =0; i< data.length; i++) {
                // var $tr = $("#nearby-deals").append("<tr>");
                // $tr.append($('#deal-name <td/>').html("<b>"+data[i].deal+" </b>"));
                // $tr.append($('<td/>').html(data[i].description+" "));
                // $tr.append($('<td/>').html(dealTimer(data[i].end_time)+"</tr>"));
                // $('.list-order tr:last').before($tr);

                var $tr = $('<tr></tr>');
                $tr.append("<td>"+data[i].deal+"</td>");
                $tr.append("<td>"+data[i].description+"</td>");
                $tr.append(dealTimer(data[i].end_time));
                $table.append($tr);

              }
              $("#nearby-deals").html($table);

            }
          });      
              
          map.setCenter(initialLocation);
        }, function() {
          handleNoGeolocation(browserSupportFlag);
        });
      }
      // Browser doesn't support Geolocation
      else {
        browserSupportFlag = false;
        handleNoGeolocation(browserSupportFlag);
      }

      function handleNoGeolocation(errorFlag) {
        if (errorFlag == true) {
          alert("Geolocation service failed.");
          initialLocation = newyork;
        } else {
          alert("Your browser doesn't support geolocation. We've placed you in Siberia.");
          initialLocation = siberia;
        }
        map.setCenter(initialLocation);
      }

      function dealTimer(expiration){
        // var self = $(expiration)
        var target_date = Math.floor(Date.parse(expiration));
        var days, hours, minutes, seconds, countdown;

        var countdown = $("<td class='deal-countdown'></td>");

        // update the tag with id "countdown" every 1 second
        setInterval(function () {
          // find the amount of "seconds" between now and target
          var current_date = new Date().getTime();
          var seconds_left = (target_date - current_date) / 1000;

          // do some time calculations
          days = parseInt(seconds_left / 86400);
          seconds_left = seconds_left % 86400;

          hours = parseInt(seconds_left / 3600);
          seconds_left = seconds_left % 3600;

          minutes = parseInt(seconds_left / 60);
          seconds = parseInt(seconds_left % 60);

          // format countdown string + set tag value
          countdown.html(days + "d, " + hours + "h, "
          + minutes + "m, " + seconds + "s");  

        }, 1000);
        return countdown;
      }

      function map_deals(dealsNearby){
        for(var i=0; i < dealsNearby.length; i++){
          var num = i+1;
          var location = new google.maps.LatLng(dealsNearby[i].latitude, dealsNearby[i].longitude);
          var dealMarker = new google.maps.Marker({
            position: location,
            map: map,
            animation: google.maps.Animation.DROP,
            icon: '/assets/number_' + num + '.png',
            title: dealsNearby[i].deal
          });
          google.maps.event.addListener(dealMarker, 'click', (function(dealMarker, i) {
            return function(){
              infowindow.setContent('<div style="height:50px; width: 100px;">'+dealsNearby[i].description+"</div>");
              infowindow.open(map,dealMarker);
            }
          })(dealMarker, i));
        }
      }
    }

    $(function() {
      initialize();

    })
    </script>
  </thead>

  <tbody id="nearby-deals-table">

    <% if false %>
      <% Deal.find(:all, :order => "id desc", :limit => 3).each do |deal|  %>
        <tr>
          <td><%= deal.deal %></td>
          <td><%= deal.description %></td>
          <td><%= link_to 'Show', deal %></td>
          <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
          <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

       <% end %>
     <% end %>
  </tbody>

  <div id='nearby-deals' class='container'>
  Loading...<br>
    <center>
      <img src="http://fc03.deviantart.net/fs71/f/2013/003/6/9/partart_loading_boredoom_6_by_g2k2007-d5q8zyt.gif" style="width:100px;"><br>
    </center>

</div>

<br>

<%= button_to 'New Deal', new_deal_path, :class =>"btn", :style => "margin-bottom: 10px", :method => "get" %>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Nearby Deals</h3>

<p>
  <strong>Deal:</strong>
  <%= @deal.deal %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @deal.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @deal.end_time %>
</p>

 <script type="text/javascript">

    var initialLocation;
    var siberia = new google.maps.LatLng(60, 105);
    var newyork = new google.maps.LatLng(40.69847032728747, -73.9514422416687);
    var browserSupportFlag =  new Boolean();


    function initialize() {
    	// alert('hello');
      var myOptions = {
        zoom: 8,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      var map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);
      var image = '/assets/smiley_happy.png';

      // Try W3C Geolocation (Preferred)
      if(navigator.geolocation) {
        browserSupportFlag = true;
        navigator.geolocation.getCurrentPosition(function(position) {
          initialLocation = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
          var Person_marker = new google.maps.Marker({
            position: initialLocation,
            title:"Where I am!",
            map: map,
            icon: image
          });     
          map.setCenter(initialLocation);
        }, function() {
          handleNoGeolocation(browserSupportFlag);
        });
      }
      // Browser doesn't support Geolocation
      else {
        browserSupportFlag = false;
        handleNoGeolocation(browserSupportFlag);
      }

      function handleNoGeolocation(errorFlag) {
        if (errorFlag == true) {
          alert("Geolocation service failed.");
          initialLocation = newyork;
        } else {
          alert("Your browser doesn't support geolocation. We've placed you in Siberia.");
          initialLocation = siberia;
        }
        map.setCenter(initialLocation);
      }

      var location = new google.maps.LatLng(<%= @deal.latitude %>, <%=@deal.longitude%>);
    	var marker = new google.maps.Marker({
        position: location,
        map: map
    	}); 

      
    }

    $(function() {
      initialize();
    })
    </script>




<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'View All Deals', deals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FlashDeals" %></title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyC4ji96n7hhtGhu0MqbJ6mLgwjXMbJoEMY&sensor=true" %>

		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">FlashDeals</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
            	
	            	<% if user_signed_in? %>
									Signed in as <%= current_user.email %> Not you?
									<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
								<% else %>
									<%= link_to 'Sign up', new_user_registration_path %> or 
									<button type="button" class="btn btn-default navbar-btn"><%= link_to 'sign in', new_user_session_path %></button>
								<% end %>
					
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
    <p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<div class="container">
			<%= yield %>
		</div>

		<div class="container">
			<div id="map-canvas"></div>
		</div>

    <div class="container">
        <div class="row">
         
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <%= f.field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :street_1 %>
      <%= f.text_field :street1 %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :state %>
      <%= f.text_field :state %>

      <%= f.label :zip %>
      <%= f.text_field :zip %>


      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/user/show.html.erb
<h1><%= @user.first_name + " " +@user.last_name %></h1>
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>
<%= @user.first_name %>, <%= @user.email %>